from __future__ import annotations

from config import settings


def list_api_sources() -> dict:
    """Return the APIs considered by the project and how they can be used.

    `map_ready` means the dataset either exposes station/event coordinates directly
    or can be mapped with a clear administrative-area/geocode join.
    """
    sources = [
        {
            "provider": "CWA",
            "dataset_id": settings.cwa_observation_dataset_id,
            "title": "有人氣象站現在天氣觀測報告",
            "category": "current_weather",
            "endpoint": f"/api/v1/rest/datastore/{settings.cwa_observation_dataset_id}",
            "status": "active",
            "map_ready": True,
            "coordinate_quality": "station_wgs84",
            "used_by": ["/api/weather/stations.geojson", "/api/weather/latest", "/api/summary/counties"],
            "metrics": ["temperature", "rainfall", "rainfall_24h", "humidity", "wind_speed", "visibility_km"],
            "note": "主要即時氣象來源；部分測站可能不回傳能見度，因此前端需容忍缺值。",
        },
        {
            "provider": "MOENV",
            "dataset_id": settings.moenv_pm25_dataset_id,
            "title": "空氣品質監測即時資料",
            "category": "air_quality",
            "endpoint": f"/api/v2/{settings.moenv_pm25_dataset_id}",
            "status": "active",
            "map_ready": True,
            "coordinate_quality": "station_wgs84_or_twd97_fields",
            "used_by": ["/api/pm25/latest", "/api/air-quality/latest", "/api/summary/counties"],
            "metrics": ["aqi", "status", "pollutant", "pm25", "pm10", "so2", "co", "o3", "no2"],
            "note": "AQI 使用環境部發布欄位，不由本系統用 PM2.5 重新推算。",
        },
        {
            "provider": "CWA",
            "dataset_id": settings.cwa_auto_station_dataset_id,
            "title": "自動氣象站即時觀測資料",
            "category": "current_weather",
            "endpoint": f"/api/v1/rest/datastore/{settings.cwa_auto_station_dataset_id}",
            "status": "candidate",
            "map_ready": True,
            "coordinate_quality": "station_wgs84",
            "used_by": [],
            "metrics": ["temperature", "rainfall", "humidity", "wind_speed"],
            "note": "適合補足 O-A0003-001 的站點密度；需要確認欄位與現有 normalization 的相容性。",
        },
        {
            "provider": "CWA",
            "dataset_id": settings.cwa_rainfall_dataset_id,
            "title": "自動雨量站雨量觀測資料",
            "category": "rainfall",
            "endpoint": f"/api/v1/rest/datastore/{settings.cwa_rainfall_dataset_id}",
            "status": "candidate",
            "map_ready": True,
            "coordinate_quality": "station_wgs84",
            "used_by": [],
            "metrics": ["rainfall", "rainfall_1h", "rainfall_3h", "rainfall_6h", "rainfall_12h", "rainfall_24h"],
            "note": "最適合做累積雨量專層；目前已先在 O-A0003-001 流程預留累積雨量欄位。",
        },
        {
            "provider": "CWA",
            "dataset_id": settings.cwa_dataset_id,
            "title": "鄉鎮天氣預報",
            "category": "forecast",
            "endpoint": f"/api/v1/rest/datastore/{settings.cwa_dataset_id}",
            "status": "optional",
            "map_ready": True,
            "coordinate_quality": "location_or_geocode_join",
            "used_by": ["/api/forecast/latest", "/api/forecast/history"],
            "metrics": ["weather", "temperature", "min_temp", "max_temp", "pop", "humidity"],
            "note": "適合做預報圖層；不是即時測站觀測，不應混在 current observation 指標中。",
        },
        {
            "provider": "CWA",
            "dataset_id": settings.cwa_sunrise_dataset_id,
            "title": "日出日沒時刻",
            "category": "astronomy",
            "endpoint": f"/api/v1/rest/datastore/{settings.cwa_sunrise_dataset_id}",
            "status": "candidate_requires_join",
            "map_ready": True,
            "coordinate_quality": "location_join_needed",
            "used_by": [],
            "metrics": ["sunrise", "sunset"],
            "note": "可做縣市或鄉鎮日出日落卡片；若原始資料未直接給經緯度，需用 geocode 或行政區中心點 join。",
        },
        {
            "provider": "CWA",
            "dataset_id": settings.cwa_warning_dataset_id,
            "title": "天氣警特報",
            "category": "warning",
            "endpoint": f"/api/v1/rest/datastore/{settings.cwa_warning_dataset_id}",
            "status": "candidate_requires_area_join",
            "map_ready": True,
            "coordinate_quality": "county_or_area_join_needed",
            "used_by": [],
            "metrics": ["warning_type", "severity", "valid_time"],
            "note": "通常是影響區域型資料，適合做縣市 polygon 或區域 badge，不一定是單一經緯度點。",
        },
        {
            "provider": "CWA",
            "dataset_id": settings.cwa_warning_area_dataset_id,
            "title": "天氣警特報影響區域",
            "category": "warning",
            "endpoint": f"/api/v1/rest/datastore/{settings.cwa_warning_area_dataset_id}",
            "status": "candidate_requires_area_join",
            "map_ready": True,
            "coordinate_quality": "county_or_area_join_needed",
            "used_by": [],
            "metrics": ["warning_area", "warning_type", "valid_time"],
            "note": "可和 W-C0033-001 搭配，用行政區面資料視覺化；不是測站點位資料。",
        },
        {
            "provider": "CWA",
            "dataset_id": settings.cwa_earthquake_report_dataset_id,
            "title": "地震報告",
            "category": "earthquake",
            "endpoint": f"/api/v1/rest/datastore/{settings.cwa_earthquake_report_dataset_id}",
            "status": "candidate",
            "map_ready": True,
            "coordinate_quality": "earthquake_epicenter",
            "used_by": [],
            "metrics": ["magnitude", "depth", "origin_time", "epicenter"],
            "note": "適合新增地震震央點位圖層；可依規模、深度、時間做篩選。",
        },
        {
            "provider": "CWA",
            "dataset_id": settings.cwa_earthquake_intensity_dataset_id,
            "title": "地震震度資料",
            "category": "earthquake",
            "endpoint": f"/api/v1/rest/datastore/{settings.cwa_earthquake_intensity_dataset_id}",
            "status": "candidate",
            "map_ready": True,
            "coordinate_quality": "station_or_area_intensity",
            "used_by": [],
            "metrics": ["intensity", "station_intensity", "area_intensity"],
            "note": "適合做震度站點或縣市震度圖層；需在實作時依 raw response 決定 station join 或 area join。",
        },
    ]
    return {"count": len(sources), "sources": sources}
