from __future__ import annotations

from config import settings


def list_api_sources() -> dict:
    sources = [
        {
            "provider": "CWA",
            "dataset_id": settings.cwa_observation_dataset_id,
            "title": "有人氣象站現在天氣觀測報告",
            "category": "current_weather",
            "endpoint": f"/api/v1/rest/datastore/{settings.cwa_observation_dataset_id}",
            "status": "active",
            "map_ready": True,
            "coordinate_quality": "測站經緯度",
            "used_by": ["/api/weather/stations.geojson", "/api/weather/latest", "/api/summary/counties"],
            "metrics": ["氣溫", "濕度", "風速", "能見度", "天氣現象"],
            "note": "中央氣象署即時地面觀測資料，用於氣象測站點位與即時天氣指標展示。",
        },
        {
            "provider": "CWA",
            "dataset_id": settings.cwa_rainfall_dataset_id,
            "title": "自動雨量站雨量觀測資料",
            "category": "rainfall",
            "endpoint": f"/api/v1/rest/datastore/{settings.cwa_rainfall_dataset_id}",
            "status": "active",
            "map_ready": True,
            "coordinate_quality": "雨量站經緯度",
            "used_by": ["/api/weather/stations.geojson", "/api/weather/latest", "/api/summary/counties", "/api/refresh/rainfall"],
            "metrics": ["短週期降雨量", "當天累積雨量"],
            "note": "中央氣象署雨量站資料，用於降雨量點位與短週期降雨監測。",
        },
        {
            "provider": "CWA",
            "dataset_id": settings.cwa_dataset_id,
            "title": "鄉鎮天氣預報",
            "category": "forecast",
            "endpoint": f"/api/v1/rest/datastore/{settings.cwa_dataset_id}",
            "status": "active",
            "map_ready": True,
            "coordinate_quality": "行政區或地理編碼位置",
            "used_by": ["/api/forecast/latest", "/api/forecast/history", "/api/refresh"],
            "metrics": ["天氣現象", "最高溫", "最低溫", "降雨機率", "濕度"],
            "note": "中央氣象署鄉鎮預報資料，用於預報查詢與歷史預報資料保存。",
        },
        {
            "provider": "MOENV",
            "dataset_id": settings.moenv_pm25_dataset_id,
            "title": "空氣品質監測即時資料",
            "category": "air_quality",
            "endpoint": f"/api/v2/{settings.moenv_pm25_dataset_id}",
            "status": "active",
            "map_ready": True,
            "coordinate_quality": "空品測站經緯度",
            "used_by": ["/api/pm25/latest", "/api/air-quality/latest", "/api/summary/counties", "/api/refresh/pm25"],
            "metrics": ["PM2.5", "PM10", "O3 8hr", "CO 8hr", "SO2", "NO2", "空品狀態"],
            "note": "環境部空氣品質監測資料，用於污染物濃度與空品測站點位展示。",
        },
        {
            "provider": "OpenStreetMap",
            "dataset_id": "OSM tile service",
            "title": "OpenStreetMap raster tiles",
            "category": "basemap",
            "endpoint": "https://tile.openstreetmap.org/{z}/{x}/{y}.png",
            "status": "active",
            "map_ready": True,
            "coordinate_quality": "Web Mercator 地圖瓦片",
            "used_by": ["OSM map mode"],
            "metrics": ["地圖底圖"],
            "note": "開放街圖地圖瓦片服務，用於 OSM 模式底圖呈現。",
        },
        {
            "provider": "Windy",
            "dataset_id": "Map Forecast API",
            "title": "Windy Map Forecast API",
            "category": "map_forecast_overlay",
            "endpoint": "https://api.windy.com/assets/map-forecast/libBoot.js",
            "status": "active",
            "map_ready": True,
            "coordinate_quality": "地圖與氣象圖層服務",
            "used_by": ["Windy map mode"],
            "metrics": ["風場背景圖層"],
            "note": "Windy 地圖服務，用於 Windy 模式的風場與氣象背景圖層呈現。",
        },
    ]
    return {"count": len(sources), "sources": sources}
